---
title: "R Notebook"
output:
html_document:
    df_print: paged
---
```{r}
library(readxl)
library(sjPlot)
library(ggplot2)
library(lme4)
library(stringr)
library(ggExtra)
```

```{r}
# linguistic data
data <- read_excel('../../data/extracted_data.xlsx')
data$Agent = ifelse(data$conv == 1,"H","R")
data = data[which(data$locutor > 1),]
data$Trial2 = paste0('t', str_pad(data$conv_id_unif, 2, pad = "0"))
```

# speech_rate
```{r}
ggplot(data, aes(x = speech_rate, color=Agent)) + facet_grid(tier ~ .) + geom_histogram(aes(y=..density..), alpha=0.5, fill="white") + geom_density(alpha=.2)
ggplot(data, aes(x = Trial2, y = speech_rate, color=Agent)) + facet_grid(tier ~ .) + geom_boxplot()
ggplot(data, 
       aes(x = Agent,
           fill = Agent,  
           y = speech_rate)) +
  stat_summary(fun.y = mean,
               geom = "bar") +
  stat_summary(fun.ymin = function(x) mean(x) - sd(x), 
               fun.ymax = function(x) mean(x) + sd(x), 
               geom="errorbar", 
               width = 0.25) +
  facet_wrap(~tier) +
  labs(x = "Agent",
       y = 'speech_rate')
```


```{r}
# creating merged data - ling
temp1 = subset(data, select = c("locutor", "conv_id_unif", "Agent", 'speech_rate'), tier=='conversant')
colnames(temp1) = c("locutor", "Trial", "Agent", "data_conv")
temp2 = subset(data, select = c("locutor", "conv_id_unif", "Agent", 'speech_rate'), tier=='participant')
colnames(temp2) = c("locutor", "Trial", "Agent", "data_part")
merres = merge(temp1, temp2, by=c("locutor", "Trial", "Agent"))
# applying mixed model
mdl = lmer('data_part ~ Agent*data_conv*Trial +(1|locutor)', data = merres)
print(summary(mdl))
tab_model(mdl, title = paste("part ~ conv ", 'speech_rate'))
#print(confint(mdl))

```
```{r}
# Setting up the building blocks
basic_plot <- ggplot(merres,
       aes(x = data_conv,
           y = data_part,
           color = Agent)) +
  theme_bw()

# Colored scatterplot and regression lines
basic_plot +
  geom_point(alpha = .3, 
             size = .9) +
  geom_smooth(method = "lm") +
  labs(x = "VI: speech_rate Conv",
       y = "VD: speech_rate Part",
       color = "Agent")
```

```{r}
# second plot
g <- ggplot(merres, aes(x = data_conv, y = data_part, color=Agent)) + 
        geom_point(alpha = 0.7) + 
        geom_density_2d(alpha=0.5) + 
        theme(legend.position="bottom") + xlim(0,max(merres$data_conv)) + ylim(0,max(merres$data_part)) +
        labs(x = "VI: speech_rate Conv",
            y = "VD: speech_rate Part",
            color = "Agent")
ggMarginal(g, type="density", margins = "both", groupColour = TRUE)
```

# speech_rate_mean
```{r}
ggplot(data, aes(x = speech_rate_mean, color=Agent)) + facet_grid(tier ~ .) + geom_histogram(aes(y=..density..), alpha=0.5, fill="white") + geom_density(alpha=.2)
ggplot(data, aes(x = Trial2, y = speech_rate_mean, color=Agent)) + facet_grid(tier ~ .) + geom_boxplot()
ggplot(data, 
       aes(x = Agent,
           fill = Agent,  
           y = speech_rate_mean)) +
  stat_summary(fun.y = mean,
               geom = "bar") +
  stat_summary(fun.ymin = function(x) mean(x) - sd(x), 
               fun.ymax = function(x) mean(x) + sd(x), 
               geom="errorbar", 
               width = 0.25) +
  facet_wrap(~tier) +
  labs(x = "Agent",
       y = 'speech_rate_mean')
```


```{r}
# creating merged data - ling
temp1 = subset(data, select = c("locutor", "conv_id_unif", "Agent", 'speech_rate_mean'), tier=='conversant')
colnames(temp1) = c("locutor", "Trial", "Agent", "data_conv")
temp2 = subset(data, select = c("locutor", "conv_id_unif", "Agent", 'speech_rate_mean'), tier=='participant')
colnames(temp2) = c("locutor", "Trial", "Agent", "data_part")
merres = merge(temp1, temp2, by=c("locutor", "Trial", "Agent"))
# applying mixed model
mdl = lmer('data_part ~ Agent*data_conv*Trial +(1|locutor)', data = merres)
print(summary(mdl))
tab_model(mdl, title = paste("part ~ conv ", 'speech_rate_mean'))
#print(confint(mdl))

```
```{r}
# Setting up the building blocks
basic_plot <- ggplot(merres,
       aes(x = data_conv,
           y = data_part,
           color = Agent)) +
  theme_bw()

# Colored scatterplot and regression lines
basic_plot +
  geom_point(alpha = .3, 
             size = .9) +
  geom_smooth(method = "lm") +
  labs(x = "VI: speech_rate_mean Conv",
       y = "VD: speech_rate_mean Part",
       color = "Agent")
```

```{r}
# second plot
g <- ggplot(merres, aes(x = data_conv, y = data_part, color=Agent)) + 
        geom_point(alpha = 0.7) + 
        geom_density_2d(alpha=0.5) + 
        theme(legend.position="bottom") + xlim(0,max(merres$data_conv)) + ylim(0,max(merres$data_part)) +
        labs(x = "VI: speech_rate_mean Conv",
            y = "VD: speech_rate_mean Part",
            color = "Agent")
ggMarginal(g, type="density", margins = "both", groupColour = TRUE)
```

# speech_rate_min
```{r}
ggplot(data, aes(x = speech_rate_min, color=Agent)) + facet_grid(tier ~ .) + geom_histogram(aes(y=..density..), alpha=0.5, fill="white") + geom_density(alpha=.2)
ggplot(data, aes(x = Trial2, y = speech_rate_min, color=Agent)) + facet_grid(tier ~ .) + geom_boxplot()
ggplot(data, 
       aes(x = Agent,
           fill = Agent,  
           y = speech_rate_min)) +
  stat_summary(fun.y = mean,
               geom = "bar") +
  stat_summary(fun.ymin = function(x) mean(x) - sd(x), 
               fun.ymax = function(x) mean(x) + sd(x), 
               geom="errorbar", 
               width = 0.25) +
  facet_wrap(~tier) +
  labs(x = "Agent",
       y = 'speech_rate_min')
```


```{r}
# creating merged data - ling
temp1 = subset(data, select = c("locutor", "conv_id_unif", "Agent", 'speech_rate_min'), tier=='conversant')
colnames(temp1) = c("locutor", "Trial", "Agent", "data_conv")
temp2 = subset(data, select = c("locutor", "conv_id_unif", "Agent", 'speech_rate_min'), tier=='participant')
colnames(temp2) = c("locutor", "Trial", "Agent", "data_part")
merres = merge(temp1, temp2, by=c("locutor", "Trial", "Agent"))
# applying mixed model
mdl = lmer('data_part ~ Agent*data_conv*Trial +(1|locutor)', data = merres)
print(summary(mdl))
tab_model(mdl, title = paste("part ~ conv ", 'speech_rate_min'))
#print(confint(mdl))

```
```{r}
# Setting up the building blocks
basic_plot <- ggplot(merres,
       aes(x = data_conv,
           y = data_part,
           color = Agent)) +
  theme_bw()

# Colored scatterplot and regression lines
basic_plot +
  geom_point(alpha = .3, 
             size = .9) +
  geom_smooth(method = "lm") +
  labs(x = "VI: speech_rate_min Conv",
       y = "VD: speech_rate_min Part",
       color = "Agent")
```

```{r}
# second plot
g <- ggplot(merres, aes(x = data_conv, y = data_part, color=Agent)) + 
        geom_point(alpha = 0.7) + 
        geom_density_2d(alpha=0.5) + 
        theme(legend.position="bottom") + xlim(0,max(merres$data_conv)) + ylim(0,max(merres$data_part)) +
        labs(x = "VI: speech_rate_min Conv",
            y = "VD: speech_rate_min Part",
            color = "Agent")
ggMarginal(g, type="density", margins = "both", groupColour = TRUE)
```

# speech_rate_max
```{r}
ggplot(data, aes(x = speech_rate_max, color=Agent)) + facet_grid(tier ~ .) + geom_histogram(aes(y=..density..), alpha=0.5, fill="white") + geom_density(alpha=.2)
ggplot(data, aes(x = Trial2, y = speech_rate_max, color=Agent)) + facet_grid(tier ~ .) + geom_boxplot()
ggplot(data, 
       aes(x = Agent,
           fill = Agent,  
           y = speech_rate_max)) +
  stat_summary(fun.y = mean,
               geom = "bar") +
  stat_summary(fun.ymin = function(x) mean(x) - sd(x), 
               fun.ymax = function(x) mean(x) + sd(x), 
               geom="errorbar", 
               width = 0.25) +
  facet_wrap(~tier) +
  labs(x = "Agent",
       y = 'speech_rate_max')
```


```{r}
# creating merged data - ling
temp1 = subset(data, select = c("locutor", "conv_id_unif", "Agent", 'speech_rate_max'), tier=='conversant')
colnames(temp1) = c("locutor", "Trial", "Agent", "data_conv")
temp2 = subset(data, select = c("locutor", "conv_id_unif", "Agent", 'speech_rate_max'), tier=='participant')
colnames(temp2) = c("locutor", "Trial", "Agent", "data_part")
merres = merge(temp1, temp2, by=c("locutor", "Trial", "Agent"))
# applying mixed model
mdl = lmer('data_part ~ Agent*data_conv*Trial +(1|locutor)', data = merres)
print(summary(mdl))
tab_model(mdl, title = paste("part ~ conv ", 'speech_rate_max'))
#print(confint(mdl))

```
```{r}
# Setting up the building blocks
basic_plot <- ggplot(merres,
       aes(x = data_conv,
           y = data_part,
           color = Agent)) +
  theme_bw()

# Colored scatterplot and regression lines
basic_plot +
  geom_point(alpha = .3, 
             size = .9) +
  geom_smooth(method = "lm") +
  labs(x = "VI: speech_rate_max Conv",
       y = "VD: speech_rate_max Part",
       color = "Agent")
```

```{r}
# second plot
g <- ggplot(merres, aes(x = data_conv, y = data_part, color=Agent)) + 
        geom_point(alpha = 0.7) + 
        geom_density_2d(alpha=0.5) + 
        theme(legend.position="bottom") + xlim(0,max(merres$data_conv)) + ylim(0,max(merres$data_part)) +
        labs(x = "VI: speech_rate_max Conv",
            y = "VD: speech_rate_max Part",
            color = "Agent")
ggMarginal(g, type="density", margins = "both", groupColour = TRUE)
```
